# Generated by Django 5.1.7 on 2025-04-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_custumer_newsletter_abo'),
    ]

    operations = [
        migrations.AddField(
            model_name='custumer',
            name='account',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custumer',
            name='email_address',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
