# Generated by Django 5.1.7 on 2025-04-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_bill_product_rename_custumer_customer_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='costumer',
            new_name='customer',
        ),
    ]
