# Generated by Django 5.1.7 on 2025-04-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_customer_options_remove_customer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_address',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='type_name',
            field=models.CharField(max_length=300),
        ),
    ]
